os: osx
language: objective-c
matrix:
  include:                                                                                        
    - {osx_image: xcode9,   env: 'Sw=4.0 Pt=iOS  Dn="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode9,   env: 'Sw=4.0 Pt=iOS  Dn="OS=11.0,name=iPhone SE"'}
    - {osx_image: xcode9,   env: 'Sw=4.0 Pt=tvOS Dn="OS=10.2,name=Apple TV 1080p"'}
    - {osx_image: xcode9,   env: 'Sw=4.0 Pt=tvOS Dn="OS=11.0,name=Apple TV 1080p"'}

    - {osx_image: xcode9,   env: 'Sw=3.2 Pt=iOS  Dn="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode9,   env: 'Sw=3.2 Pt=iOS  Dn="OS=11.0,name=iPhone SE"'}
    - {osx_image: xcode9,   env: 'Sw=3.2 Pt=tvOS Dn="OS=10.2,name=Apple TV 1080p"'}
    - {osx_image: xcode9,   env: 'Sw=3.2 Pt=tvOS Dn="OS=11.0,name=Apple TV 1080p"'}

    - {osx_image: xcode8.3, env: 'Sw=3.1 Pt=iOS  Dn="OS=10.3.1,name=iPhone SE"'}
    - {osx_image: xcode8.3, env: 'Sw=3.1 Pt=iOS  Dn="OS=9.0,name=iPhone 6"'}
    - {osx_image: xcode8.3, env: 'Sw=3.1 Pt=iOS  Dn="OS=8.1,name=iPhone 4S"'}
    - {osx_image: xcode8.3, env: 'Sw=3.1 Pt=tvOS Dn="OS=10.2,name=Apple TV 1080p"'}  
    - {osx_image: xcode8.3, env: 'Sw=3.1 Pt=tvOS Dn="OS=9.0,name=Apple TV 1080p"'}  

    - {osx_image: xcode8.2, env: 'Sw=3.0 Pt=iOS  Dn="OS=10.2,name=iPhone SE"'}
    - {osx_image: xcode8.2, env: 'Sw=3.0 Pt=tvOS Dn="OS=10.1,name=Apple TV 1080p"'}

install:
  - carthage bootstrap --platform $Pt
script:
  - xcodebuild -scheme PMKUIKit -quiet -destination "$Dn" build SWIFT_VERSION="$Sw"
